on:
  push:
    paths:
      - 'bot/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bot_image


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build JAR
        run: mvn -DskipTests=true package -pl bot -am
      - name: Build Image
        run: docker build -q -t $REGISTRY/trofimtyulkin/$IMAGE_NAME:latest . -f bot.Dockerfile
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_PASSWORD}}

      - name: 'Push Inventory Image'
        run: |
          docker push $REGISTRY/trofimtyulkin/$IMAGE_NAME:latest
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven and check
        run: mvn -pl bot -am checkstyle:check
        working-directory: tinkoff-education

